* ~git-config-manager~
=git-config-manager= is a tool for setting git configurations by schemes described
in =json= file. It is useful in situations when you can specify different sets of
configurations for different repositories (like work, personal etc) and want to
avoid typing configurations by hand for every single repository.

For example, consider following content in
~$XDG_CONFIG_HOME/git/git-config-manager.json~ (which is loaded by default if you
don't override it using =--config-file= option).

#+BEGIN_SRC json
{
  "personal": {
    "user": {
      "name": "The Donkey",
      "email": "mybossdontknowme@protonmail.ch",
      "signingkey": "ABCDEFGH"
    }
  },
  "my_project": {
    "pull": {
      "rebase": true
    }
  },
  "work": {
    "user": {
      "name": "Mr. Doe",
      "email": "slave012345@corp.me",
      "signingkey": "ABCDEFGH"
    },
    "pull": {
      "rebase": null
    }
  }
}
#+END_SRC

You can navigate to any repository and call ~git-config-manager set personal~ to
set all configurations under ~personal~ scheme.

Note that supported value types are strings, numbers and booleans. If you set
the value to =null=, it will be unset (and in case corresponding section is empty
it will be also removed).

** Interface

#+BEGIN_EXAMPLE
$ git-config-manager --help
Git configuration manager

Usage: git-config-manager [--verbose] [--config-file PATH] COMMAND
  Manage git configurations and switch between them with ease

Available options:
  -h,--help                Show this help text
  --verbose                Enable verbose mode
  --config-file PATH       Specify configuration file path

Available commands:
  list                     List all available configuration schemes
  get                      Get name of currently used scheme
  set                      Set up configurations by scheme
#+END_EXAMPLE

** Install

The easiest way to install ~git-config-manager~ is to use [[https://github.com/commercialhaskell/stack][stack]].

#+BEGIN_SRC shell
$ git clone https://github.com/d12frosted/git-config-manager.git
$ cd git-config-manager
$ stack install
#+END_SRC

* ~Magit~ interface

Git configuration manager comes with =magit= interface. It just adds new section
to status buffer. All available actions are available under ~C~ key. In order to
set configuration scheme selected desired scheme and press ~C s~. In order to
unset it - ~C u~.

** Install

While package is not available on MELPA, one can install it using ~quelpa~.
After ~magit-gcm~ is available on your ~load-path~, just add following snippet
to your ~init.el~.

#+BEGIN_SRC emacs-lisp
(require 'magit-gcm)
(add-hook 'magit-mode-hook 'turn-on-magit-gcm)
#+END_SRC
